export const presets = {
	default: {
		name: "Default",
		description: "Balanced preset",
		params: {
			volume: 40,
			color: 5,
			speechMask: 6,
			presence: 4,
			ampMod: true,
			modDepth: 8,
			modSpeed: 90,
			fletcherMunson: true,
			resonance: true,
			stereo: 30,
			bassBoost: 5,
			highCut: 4000,
		},
	},
	deepFocus: {
		name: "Deep Focus",
		description: "Maximum masking for noisy environments",
		params: {
			volume: 25,
			color: 12,
			speechMask: 6,
			presence: 4,
			ampMod: true,
			modDepth: 8,
			modSpeed: 90,
			fletcherMunson: true,
			resonance: true,
			stereo: 30,
			bassBoost: 4,
			highCut: 8000,
		},
	},
	lightBackground: {
		name: "Light Background",
		description: "Gentle, unobtrusive ambient sound",
		params: {
			volume: 25,
			color: 25,
			speechMask: 2,
			presence: 1,
			ampMod: true,
			modDepth: 20,
			modSpeed: 45,
			fletcherMunson: true,
			resonance: false,
			stereo: 60,
			bassBoost: 2,
			highCut: 12000,
		},
	},
	sleep: {
		name: "Sleep Mode",
		description: "Deep, consistent sound for rest",
		params: {
			volume: 25,
			color: 8,
			speechMask: 5,
			presence: 0,
			ampMod: false,
			modDepth: 5,
			modSpeed: 120,
			fletcherMunson: true,
			resonance: false,
			stereo: 10,
			bassBoost: 6,
			highCut: 4000,
		},
	},
	creative: {
		name: "Creative Work",
		description: "Inspiring variation for creative tasks",
		params: {
			volume: 25,
			color: 20,
			speechMask: 3,
			presence: 3,
			ampMod: true,
			modDepth: 25,
			modSpeed: 40,
			fletcherMunson: true,
			resonance: true,
			stereo: 70,
			bassBoost: 3,
			highCut: 10000,
		},
	},
	custom: {
		name: "Custom",
		description: "Your personalized settings",
		params: null,
	},
};

